### ISSUE TITLE
opensource your backend

### ISSUE THREAD

**Issue by pejman-hkh** [webtor-io/chrome-ext#1]
Does you proxy torrent over http ?

**Comment by vintikzzz** [comment]
Yes

**Comment by pejman-hkh** [comment]
> Yes

is very good project, i so try to do this, but i have not time to complete it. do you opensource it ?

**Comment by vintikzzz** [comment]
Yes, I am going to do so, but it can take a long time. I have to do a lot of code cleaning before it. It is quite hard to implement new features, opensource project components and do a full-time work at the same time. Thank you for your interest to my project!

**Comment by pejman-hkh** [comment]
Is very good. thank you. i will wait for it...

**Comment by bcashier** [comment]
We can help to clean it up... u will have many contributors for this kind of project.

**Comment by bcashier** [comment]
@vintikzzz 

Another question please:

How much concurrent usage supported and how many servers required to handle them? And specs of servers if possible.

Thanks
