### ISSUE TITLE
How the video is streamed while not fully downloaded

### ISSUE THREAD

**Issue by bcashier** [webtor-io/chrome-ext#2]
Hi,

I read technical details on your blog, but I still not undetand how u managed to solve this puzzle:

For example I have a 2h video, and when I click on the five last minutes for example of the video, it is streamed without been fully downloaded (and transcoded in same time).

Do you download a part of the torrent file alone calculating the time for where to start the download or waiting for the torrent to be fully downloaded in order to manipulate it?

Thanks again

**Comment by vintikzzz** [comment]
Hi!
FFmpeg has seeking ability, even for http-resources.
So what is happeining there:
1. User selects specific time, for example 3:43
2. This time coresponds to specific HLS-fragment, in this case this fragment starts at 3:40
3. FFmpeg starts HLS-transcoding starting from 3:40. It uses seeking here without downloading full file via http.
4. When first fragment (3:40-3:45) is ready it is streamed to the user and so on.

**Comment by bcashier** [comment]
@vintikzzz How do you calculate and specify the right piece of file to download based on the time choosen by user?

Thanks

**Comment by vintikzzz** [comment]
Here is a [great article](https://trac.ffmpeg.org/wiki/Seeking) for FFmpeg seeking 
For previous example I just use `-ss 3:40` flag before input

**Comment by bcashier** [comment]
@vintikzzz I mean how to choose the right input,

For example the file to stream have 5gb, and only 1% downloaded... the user select the 5 last minutes of the video (that are not downloaded yet)... how u are processing in this case please?

Thanks again in advance
